version: 0.0.{build}
max_jobs: 4
image:
- Ubuntu
- Visual Studio 2019
platform: x64
environment:
  matrix:

  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019
    
  - job_name: Android build
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu    
  
for:
-
  matrix:
    only:
      - job_name: Linux build
      
  build_script:
  - ps:
    - "Linux build script" | Out-Host
    - cd dependencies
    - sudo apt-get update
    - sudo apt-get --assume-yes install libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - sh download_dependencies.sh
    - cd ../
    - mkdir build
    - cd build
    - cmake ../
    - make
-
  matrix:
    only:
      - job_name: Windows build
      
  build_script:
  - ps:
    - "Windows build script" | Out-Host
    - cd dependencies
    - ./download_dependencies.ps1
    - cd ../
    - mkdir build
    - cd build
    - cmake ../ -DBUILD_SHARED_LIBS=OFF -A x64 
    - MSBuild.exe ALL_BUILD.vcxproj
-
  matrix:
    only:
      - job_name: Android build
      
  install:
    - appveyor DownloadFile https://dl.google.com/android/repository/platform-tools-latest-windows.zip
    - 7z x platform-tools-latest-windows.zip -oC:\android-sdk-windows > nul
    - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses
      
  build_script:
  - ps:
    - "Android build script" | Out-Host
    - cd platform/android
    - gradlew.bat assemble
  
deploy: off