version: 0.0.{build}
max_jobs: 4  
environment:
  matrix:

  - job_name: Android build
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu    
  
platform: x64

﻿configuration:
  - Debug
  - Release  

for:
-
  matrix:
    only:
      - job_name: Linux build
      
  build_script:
  - ps:
  - ps: Write-Host "Linux build script"
  - ps: cd dependencies
  - ps: sudo apt-get update
  - ps: sudo apt-get --assume-yes install libglu1-mesa-dev freeglut3-dev mesa-common-dev
  - ps: sh download_dependencies.sh
  - ps: cd ../
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -Wno-dev ../
  - ps: Write-Host "Starting build"
  - ps: make
-
  matrix:
    only:
      - job_name: Windows build
      
  build_script:
  - ps: Write-Host "Windows build script"
  - ps: cd dependencies
  - ps: ./download_dependencies.ps1
  - ps: cd ../
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -Wno-dev ../ -DBUILD_SHARED_LIBS=OFF -A x64
  - ps: Write-Host "Starting build"
  - ps: MSBuild.exe ALL_BUILD.vcxproj
-
  matrix:
    only:
      - job_name: Android build
      
  # Installation of current tools. Needs to be copied into %ANDROID_HOME%/cmdline-tools. 
  # Versions of CMake and NDK might change in the future. Check sdkmanager.bat --list
  install:
    - appveyor DownloadFile https://dl.google.com/android/repository/commandlinetools-win-6609375_latest.zip
    - mkdir C:\android-sdk-windows
    - 7z x commandlinetools-win-6609375_latest.zip -oC:\android-sdk-windows\cmdline-tools > nul 
    - yes | C:\android-sdk-windows\cmdline-tools\tools\bin\sdkmanager.bat --licenses
    - yes | C:\android-sdk-windows\cmdline-tools\tools\bin\sdkmanager.bat --install "cmake;3.10.2.4988404" "ndk;18.1.5063045"
  build_script:
  - ps: Write-Host "Android build script"
  - ps: cd dependencies
  - ps: ./download_dependencies.ps1
  - ps: cd ../
  - ps: $env:ANDROID_HOME="C:\\android-sdk-windows"
  - ps: cd platform/android
  - ps: Write-Host "Starting build"
  - ps: ./gradlew.bat assemble
  
deploy: off