version: 0.0.{build}
max_jobs: 4

platform: x64

environment:
  matrix:

  - job_name: Android build Release
    job_group: Android build
    configuration: Release
    appveyor_build_worker_image: Visual Studio 2019
    
  - job_name: Android build Debug
    job_group: Android build
    configuration: Debug
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Windows build Release
    job_group: Windows build
    configuration: Release
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Windows build Debug
    job_group: Windows build
    configuration: Debug
    appveyor_build_worker_image: Visual Studio 2019
    
  - job_name: Linux build Release
    job_group: Linux build
    configuration: Release
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build Debug
    job_group: Linux build
    configuration: Debug
    appveyor_build_worker_image: Ubuntu
  
for:
-
  matrix:
    only:
      - job_group: Linux build
      
  build_script:
  - ps: |
      cd dependencies      
      sudo apt-get update      
      sudo apt-get --assume-yes install libglu1-mesa-dev freeglut3-dev mesa-common-dev      
      sh download_dependencies.sh      
      cd ../      
      mkdir build      
      cd build      
      cmake -Wno-dev ../      
      make
-
  matrix:
    only:
      - job_group: Windows build
      
  build_script:
  - ps: |
      cd dependencies      
      ./download_dependencies.ps1      
      cd ../      
      mkdir build      
      cd build
      cmake -Wno-dev ../ -DBUILD_SHARED_LIBS=OFF -A x64      
      MSBuild.exe ALL_BUILD.vcxproj
-
  matrix:
    only:
      - job_group: Android build
        configuration: Release
      
  # Installation of current tools. Needs to be copied into %ANDROID_HOME%/cmdline-tools. 
  # Versions of CMake and NDK might change in the future. Check sdkmanager.bat --list
  install:
    - appveyor DownloadFile https://dl.google.com/android/repository/commandlinetools-win-6609375_latest.zip
    - mkdir C:\android-sdk-windows
    - 7z x commandlinetools-win-6609375_latest.zip -oC:\android-sdk-windows\cmdline-tools > nul 
    - yes | C:\android-sdk-windows\cmdline-tools\tools\bin\sdkmanager.bat --licenses
    - yes | C:\android-sdk-windows\cmdline-tools\tools\bin\sdkmanager.bat --install "cmake;3.10.2.4988404" "ndk;18.1.5063045"
  build_script:
    - ps: |
        cd dependencies      
        ./download_dependencies.ps1      
        cd ../      
        $env:ANDROID_HOME="C:\\android-sdk-windows"      
        $env:ANDROID_NDK_HOME="C:\\android-sdk-windows\\ndk-bundle"
        $env:JAVA_HOME="C:\\Program Files\\Java\\jdk1.8.0"
        cd platform/android    
    - gradlew.bat assembleRelease --warning-mode=none --offline

-
  matrix:
    only:
      - job_group: Android build
        configuration: Debug
      
  # Installation of current tools. Needs to be copied into %ANDROID_HOME%/cmdline-tools. 
  # Versions of CMake and NDK might change in the future. Check sdkmanager.bat --list
  install:
    - appveyor DownloadFile https://dl.google.com/android/repository/commandlinetools-win-6609375_latest.zip
    - mkdir C:\android-sdk-windows
    - 7z x commandlinetools-win-6609375_latest.zip -oC:\android-sdk-windows\cmdline-tools > nul 
    - yes | C:\android-sdk-windows\cmdline-tools\tools\bin\sdkmanager.bat --licenses
    - yes | C:\android-sdk-windows\cmdline-tools\tools\bin\sdkmanager.bat --install "cmake;3.10.2.4988404" "ndk;18.1.5063045"
  build_script:
    - ps: |
        cd dependencies      
        ./download_dependencies.ps1      
        cd ../      
        $env:ANDROID_HOME="C:\\android-sdk-windows"      
        $env:ANDROID_NDK_HOME="C:\\android-sdk-windows\\ndk-bundle"
        $env:JAVA_HOME="C:\\Program Files\\Java\\jdk1.8.0"
        cd platform/android    
    - gradlew.bat assembleDebug
  
deploy: off